#################################################################
#
# Build configuration file for POT3D on Hopper with NVIDIA GPUs
#
#################################################################
# MPI Fortran compiler
#################################################################

FC: mpifort

###########################################################################
# Compile flags for NVIDIA HPC SDK with GPU support
###########################################################################

FRTFLAGS: -O3 -mp=gpu -acc=gpu -stdpar=gpu -gpu=cc90,managed -Minfo=accel

#################################################################
# HDF5 library location
#################################################################

HDF5_INCLUDE_DIR: /home/ac.zzheng/hdf5-nvhpc/include
HDF5_LIB_DIR: /home/ac.zzheng/hdf5-nvhpc/lib

##################################################################
# HDF5 linker flags
##################################################################

HDF5_LIB_FLAGS: -lhdf5hl_fortran -lhdf5_fortran -lhdf5_hl -lhdf5 -lz -ldl

###########################################################################
# Enable cuSparse library for ~2x speed improvement
# Set ifprec=2 in pot3d.dat when using this option
###########################################################################

USE_CUSPARSE: 1
CCFLAGS: -O3 -mp=gpu -gpu=cc90,managed -Minfo=accel
